rmw_cyclonedds_cpp/src/rmw_node.cpp
Reduce memory usage by:
* Having only a single set of readers for the built-in topics, instead of one per RMW node. The existence of a reader means that there will be instances, and with many nodes, that adds up.
* Create a single DDS subscriber and a single DDS publisher per RMW node, instead of letting those implicitly be created for each DDS reader/writer. While doesn't add up to much, when there are many endpoints, it does make a difference.
=> Use less memory

rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport.hpp, rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp, rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdata.hpp, rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdes.hpp, rmw_cyclonedds_cpp/src/rmw_node.cpp, rmw_cyclonedds_cpp/src/serdata.cpp, rmw_cyclonedds_cpp/src/serdes.cpp
=> Uncrustify and fix issues reported by cpplint

rmw_cyclonedds_cpp/src/rmw_node.cpp
=> Support creating a waitset without creating a node

rmw_cyclonedds_cpp/CMakeLists.txt, rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport.hpp, rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp, rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdes.hpp, rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/u16string.hpp, rmw_cyclonedds_cpp/src/u16string.cpp
=> Add wstring support

README.md, cyclonedds_cmake_module/package.xml, cyclonedds_vendor/CMakeLists.txt, cyclonedds_vendor/package.xml, rmw_cyclonedds_cpp/CMakeLists.txt, rmw_cyclonedds_cpp/package.xml
Recommend resolving and installing dependencies with rosdep instead of apt.
=> Use rosdep

rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdes.hpp
=> Fix "type punning" warning in printing floats

rmw_cyclonedds_cpp/src/serdes.cpp
Some code improvements in ser/deser code wrt passing data size to cycdeserbase class.
Signed-off-by: Dennis Potman <dennis.potman@adlinktech.com>
=> Code improvements in ser/deser code wrt passing data size

rmw_cyclonedds_cpp/src/rmw_node.cpp
As the title says, add the localhost boolean parameter for the create node function. Connected to [this](https://github.com/ros2/ros2/issues/798)
=> Add localhost boolean parameter to create node function

rmw_cyclonedds_cpp/CMakeLists.txt, rmw_cyclonedds_cpp/src/rmw_node.cpp
PR #50 broke CycloneDDS on Dashing. This fixes it.
=> unbreak Dashing build after #50

rmw_cyclonedds_cpp/src/rmw_node.cpp
Fix some lint error in `rmw_node.cpp`
Signed-off-by: evshary <evshary@gmail.com>
=> Solve the lint issue.

rmw_cyclonedds_cpp/src/rmw_node.cpp
This PR implements the "localhost only" feature of https://github.com/ros2/ros2/issues/798 for which the interface change was introduced into rmw_cyclonedds by #50. I am not entirely happy with the interface in Cyclone, so there'll likely be a follow-up when Cyclone's interface is fixed, but that'll be trivial.
It should avoid the problem of hard-coded IP address (as discussed in https://github.com/ros2/ros2/issues/798#issuecomment-544596424 and the comments that follow) by relying on the name "localhost", but that assumes hostname lookup for "localhost" always succeeds. That seems like a pretty reasonable assumption. In any case, configuration overrides can still be done the normal way, so on machines where "localhost" doesn't resolve correctly, there is a fallback.
=> Support localhost-only communications

rmw_cyclonedds_cpp/src/rmw_node.cpp
Caused by my "future proofing"  it …
=> Fix dashing breakage

rmw_cyclonedds_cpp/src/rmw_node.cpp
Cyclone's original code for dds_create_domain() appears to create a domain entity that is automatically deleted when the last attached participant disappears.  In reality, it leaks a reference while returning DDS_RETCODE_OK, making it appear as-if it is a regular entity that remains into existence until explicitly deleted.
The RMW code assumed that it would be automatically deleted when the last node was destroyed and that a subsequent call to rmw_create_node could create the domain anew.  This then fails with "precondition not met".
In an upcoming fixed version of dds_create_domain() the domain entities will behave normally (return a handle, require an explicit delete).
This commit provides a workaround for the bug in the original implementation: by recovering the handle from the first …
=> Address "Precondition not met" on rmw_create_node (#65)

rmw_cyclonedds_cpp/CMakeLists.txt
=> Minor CMakeLists cleanup

rmw_cyclonedds_cpp/src/rmw_node.cpp
=> Fix uncrustify error

rmw_cyclonedds_cpp/src/serdata.cpp
This is a companion to https://github.com/eclipse-cyclonedds/cyclonedds/pull/382, implementing the small interface extension for custom topic implementations it requires.
I've verified that the RMW layer with this change applied doesn't break anything (I guess it is pretty obvious from the changes that it won't) when used with a version of cyclone that doesn't have the aforementioned PR applied. Without this PR it won't work with an updated cyclone, so it should be merged before the cyclone PR gets merged. I would prefer to wait until the latter one has had a chance of getting reviewed, just in case there will be changes affecting this PR.
For me locally, using Foxy and Melodic on Ubuntu 18.04, this makes the ros1 bridge demo described in the readme at https://github.com/ros2/ros1_bridge …
=> Support ros1-bridge (#72)

rmw_cyclonedds_cpp/src/rmw_node.cpp, rmw_cyclonedds_cpp/src/serdata.cpp
Since the CI [test failure](http://build.ros2.org/view/Fci/job/Fci__nightly-cyclonedds_ubuntu_focal_amd64/15/testReport/rmw_cyclonedds_cpp/uncrustify/src_rmw_node_cpp/), make some modification to fulfill the test.
=> Correct the coding style to pass CI test.

rmw_cyclonedds_cpp/src/rmw_node.cpp
Updated after https://github.com/ros2/rmw/pull/196.
=> Update usage of rmw_topic_endpoint_info_array

rmw_cyclonedds_cpp/src/rmw_node.cpp
Fix issue with sertopic usage that was uncovered by https://github.com/ros2/rcl/issues/585. This PR fixes the issue by using `dds_create_topic_generic` (introduced by https://github.com/eclipse-cyclonedds/cyclonedds/pull/422) for creating the topic, so that the sertopic that is actually used (which could be different from the sertopic passed to `dds_create_topic_generic`) can be referenced in the ros publisher.
=> Fix sertopic referencing

rmw_cyclonedds_cpp/src/serdata.cpp
The security specification has a mode in which keyhashes containing the
MD5 of the key value are required on the wire, and this requires some
small changes to the topic interface.  Currently, these changes reside
only on the security branch of Cyclone DDS.
The changes use conditional compilation to handle both the master branch
of Cyclone and the security branch to minimise version dependencies.
=> Update for building against the "security" branch of Cyclone DDS

rmw_cyclonedds_cpp/package.xml
There are some unnecessary dependencies and some missing runtime dependencies. This PR tames the mess
=> Clean up package xml dependencies

.github/workflows/CI.yml, README.md
Fix https://github.com/ros2/rmw_cyclonedds/issues/128
=> Change branching strategy

rmw_cyclonedds_cpp/CMakeLists.txt, rmw_cyclonedds_cpp/src/fallthrough_macro.hpp, rmw_cyclonedds_cpp/src/rmw_node.cpp
as per https://github.com/ros2/rmw_cyclonedds/pull/149#issuecomment-613130793
=> Make case fallthrough explicit

.github/workflows/CI.yml
=> [Dashing-Eloquent] Bump ci setup-ros to 0.0.19

rmw_cyclonedds_cpp/src/rmw_node.cpp
Implements https://github.com/ros2/rmw/pull/217
=> implement with_info version of take

.github/workflows/CI.yml
Prevent build errors seen in: https://github.com/ros-tooling/setup-ros/issues/157
=> Cache chocolatey packages to reduce flakiness

.github/workflows/CI.yml
This ensures we maintain compatibility with downstream
=> Add rmw_implementation to CI workflow

rmw_cyclonedds_cpp/src/rmw_node.cpp
To comply with https://github.com/ros2/rmw/pull/243.
=> Ensure compliant init/shutdown API implementations.

rmw_cyclonedds_cpp/src/rmw_node.cpp
See https://github.com/ros2/rcl/pull/708.
=> Remove domain_id and localhost_only from node API

rmw_cyclonedds_cpp/src/rmw_node.cpp
Precisely what the title says. Split from #223.
=> Change RET_WRONG_IMPLID() to return RMW_RET_INCORRECT_IMPLEMENTATION

rmw_cyclonedds_cpp/src/rmw_node.cpp
Connected to https://github.com/ros2/rmw/pull/262.
=> Ensure compliant matched pub/sub count API.

.github/workflows/CI.yml
=> Don't run CI for documentation-only changes

rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport.hpp, rmw_cyclonedds_cpp/src/serdata.cpp
=> Use quotes for non-system includes

rmw_cyclonedds_cpp/src/rmw_node.cpp
=> Updated error returns on rmw_publish_serialized_message to comply with documentation

CYCLONEDDS_QUALITY_DECLARATION.md
Updated to provide missing information and clarifications.
@eboasson @rotu
=> Add quality declaration for Cyclone DDS

rmw_cyclonedds_cpp/src/rmw_node.cpp
=> Updated error returns on rmw_take

rmw_cyclonedds_cpp/src/TypeSupport_impl.hpp
See https://github.com/ros2/rosidl/pull/531.
=> Fix array `get_function` semantics

rmw_cyclonedds_cpp/src/rmw_node.cpp
=> [foxy] rmw_destroy_node must remove node from graph cache

rmw_cyclonedds_cpp/src/rmw_node.cpp
Drop invalid pointers.
Signed-off-by: Michel Hidalgo <michel@ekumenlabs.com>
=> [Backport Foxy] Fix context cleanup. (#227)

rmw_cyclonedds_cpp/src/rmw_node.cpp
Fixes https://github.com/ros2/rmw_cyclonedds/issues/264.
Bug introduced in https://github.com/ros2/rmw_cyclonedds/pull/255.
=> Delete assert line that may fail

rmw_cyclonedds_cpp/src/rmw_node.cpp
Implements https://github.com/ros2/rmw/pull/299
Depends on https://github.com/ros2/rmw_dds_common/pull/45
=> Add RMW function to check QoS compatibility

CYCLONEDDS_QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
=> Updating Quality Declaration

rmw_cyclonedds_cpp/src/TypeSupport_impl.hpp, rmw_cyclonedds_cpp/src/rmw_node.cpp, rmw_cyclonedds_cpp/src/serdata.cpp, rmw_cyclonedds_cpp/src/serdata.hpp
=> Fix zero copy issues

shared_memory_support.md
=> Added shared memory support usage description

rmw_cyclonedds_cpp/src/rmw_node.cpp
Connected to https://github.com/ros2/rmw/pull/313.
=> Update rmw_context_impl_t definition

rmw_cyclonedds_cpp/package.xml
Precisely what the title says.
=> Update package maintainers

rmw_cyclonedds_cpp/QUALITY_DECLARATION.md
@eboasson updated version number 1.0.0 and quality level 3
=> updated version number and quality level

rmw_cyclonedds_cpp/src/rmw_node.cpp
Signed-off-by: Mauro Passerino <mpasserino@irobot.com>
=> Add client/service QoS getters

rmw_cyclonedds_cpp/src/Serialization.cpp, rmw_cyclonedds_cpp/src/serdata.cpp
Links to https://github.com/ament/uncrustify_vendor/pull/27 ; see that PR for more information and CI.
=> Updates for uncrustify 0.72

rmw_cyclonedds_cpp/CHANGELOG.rst, rmw_cyclonedds_cpp/package.xml
Once approved, I'd like to fast-forward merge this PR and push the tag myself. I can do the bloom release, as well. All I need is maintainer approval.
=> 0.22.4 (Galactic)

rmw_cyclonedds_cpp/src/TypeSupport.cpp, rmw_cyclonedds_cpp/src/TypeSupport_impl.hpp, rmw_cyclonedds_cpp/src/rmw_node.cpp, rmw_cyclonedds_cpp/src/serdes.hpp
Relates to https://github.com/ament/ament_lint/pull/324
=> Fix cpplint errors

rmw_cyclonedds_cpp/src/rmw_node.cpp
=> [foxy] Free with the same allocator in rmw_destroy_node (#355)

rmw_cyclonedds_cpp/src/rmw_node.cpp
=> [galactic] Free with the same allocator in rmw_destroy_node (#355)

rmw_cyclonedds_cpp/src/rmw_node.cpp
Related to https://github.com/ros2/design/pull/282 to add content-filtered-topic interfaces.
=> Add content filter topic feature empty stub

rmw_cyclonedds_cpp/src/rmw_node.cpp
This updates #429 to match the revised requirements matrix that was recommended [in this post](https://discourse.ros.org/t/proposed-changes-to-how-ros-performs-discovery-of-nodes/27640/25) on the discourse thread.
=> Revisions for changes to peer discovery changes

rmw_cyclonedds_cpp/src/rmw_node.cpp
This updates the discovery options PR to match the upstream API changes that have been iterating in https://github.com/ros2/rmw/pull/349
=> Update to new rmw_discovery_options API

rmw_cyclonedds_cpp/src/rmw_node.cpp
These can't successfully be set on the entities right now, so just skip them.
Also make sure to check for errors when setting the status mask, which should help surface this kind of problem in the future.
I'll note that we are kind of lying here; we are telling the upper rcl/rclpy/rclpp layers that we support the INCOMPATIBLE_TYPE events, but then we are failing to register for it down below.  But I think that is a reasonable compromise here.
@eboasson I'm especially interested on your take for this fix.
This replaces https://github.com/ros2/rmw_cyclonedds/pull/442 .  @Crola1702 FYI
=> Disable inconsistent topic events.

rmw_cyclonedds_cpp/src/rmw_node.cpp
Part of ros2/ros2#1159
Depends on ros2/rosidl#727 (and is bundled with)
=> Use get_type_hash_func on typesupports (rep2011)

rmw_cyclonedds_cpp/src/rmw_node.cpp
Depends on https://github.com/ros2/ros2_tracing/pull/74
For some background: https://github.com/ros2/ros2_tracing/issues/73
Question: Has `dds_write_ts` + `dds_time()` any drawbacks if compared with using plain `dds_write`?
=> Add timestamp to rmw_publish tracepoint

rmw_cyclonedds_cpp/src/serdata.cpp
address https://github.com/ros2/rmw_fastrtps/issues/742
=> compare string contents but string pointer addresses.

rmw_cyclonedds_cpp/src/rmw_node.cpp
comes with https://github.com/ros2/rcl/pull/1169
this PR comes from forked one, since i do not have permission to https://github.com/ros2/rmw_cyclonedds
=> remove rmw_localhost_only_t.
