- rmw_cyclonedds_cpp/src/rmw_node.cpp
Sometimes dds_qget_userdata() returns true with a nullptr. It might be a good idea to revise its implementation.
> Fix segfault when using rmw_get_node_names()

- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
Replace `__attribute__ ((unused))` with `static_cast<void>`.
Signed-off-by: Hunter L. Allen <hunterlallen@protonmail.com>
---
Connects to #11 -- though this isn't a full fix.
> Improve Windows 10 Support

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Misuse of std::vector resize as if it would leave any reserved entries
unchanged caused a misinterpretation of entries whenever the number of
triggering entities was larger than the number of triggering entities in
the preceding call to rmw_wait: these would all be mapped to the first
entity in the set.
If the waitset is reused from call to call and spurious events are
handled gracefully, this is recoverable; otherwise, no such luck.
Moreover, not accounting for a sentinel entry added to the list of
triggered entities means it would never return RMW_RET_TIMEOUT.
> Fix return of rmw_wait

- rmw_cyclonedds_cpp/src/rmw_node.cpp
The built-in topics readers in the RMW node are currently not used for
anything other than triggering the guard condition.  All the query
functions just get their own data set from Cyclone.  Taking all samples
instead of just the not-alive ones reduces memory usage.
> Don't retain all data in builtin-topics readers

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdes.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
This set of commits addresses a number of test failures and adds get_client_names_and_types_by_node for compatibility with current master/Eloquent.
> Various fixes for test failures and compatibility with Eloquent

- rmw_cyclonedds_cpp/src/rmw_node.cpp
* RMW_QOS_POLICY_DEPTH_SYSTEM_DEFAULT was not handled, causing some failures in reader/writer creation;
* waiting on an "empty" waiset behaves differently, attaching an otherwise unused guard condition to the RMW wait sets brings Cyclone RMW behaviour in line with RCL expectations;
* implement ``rmw_take_event`` — the underlying events are not yet generated by Cyclone, but the interfaces to retrieve the data are available, so it is better to implement it properly
> Address a few items

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdata.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
- rmw_cyclonedds_cpp/src/serdes.cpp
This pull request address two interoperability issues:
* The serialization format was set incorrectly (to parameterized CDR ...) — oops;
* The rest-of-the-world incorrectly (for DDS, not necessarily for ROS2) uses the "NO_KEY" variants for reader/writer GUIDs whereas Cyclone stuck with the "WITH_KEY" variant. This way, interop is never going to work properly, and so Cyclone has submitted to the tyranny of the majority. This necessitated a change in the interfaces for custom topic implementations. The code is source-compatible with both versions of the interfaces in Cyclone.
I'm not sure this fixes all issues, but it is certainly sufficient to make things start working.
The reset is dull details.
> Interoperate with other DDS implementations

- rmw_cyclonedds_cpp/package.xml
Commit 1200bfd109e4e21ff572ce0c6205cb6c2e247edc in Cyclone DDS changed
the setting of the project name to use a string literal.  That change
affects the capitalization of the name under which colcon looks for
Cyclone, and this commit changes the dependency specification to match.
> Replace cyclonedds by CycloneDDS for colcon

- cyclonedds_cmake_module/package.xml
- rmw_cyclonedds_cpp/package.xml
In order for Bloom to release the packages in this repository, they must all carry the same version number.
Additionally, tagging that version in Git makes that process significantly easier, and is highly recommended when you're ready to release these packages.
> Prepare rmw_cyclonedds for release in ROS 2

- rmw_cyclonedds_cpp/CMakeLists.txt
- rmw_cyclonedds_cpp/src/rmw_node.cpp
```
Failed: rmw_cyclonedds_cpp.lint_cmake.whitespace/extra (CMakeLists.txt:36)
Extra spaces between 'if' and its ()
```
```
Failed: rmw_cyclonedds_cpp.uncrustify.src/rmw_node.cpp
Diff with 10 lines
--- src/rmw_node.cpp
+++ src/rmw_node.cpp.uncrustify
@@ -72,2 +72,2 @@
-#define RET_NULL_X(var, code) do {if (!var) RET_ERR_X (#var " is null", code);} while (0)
-#define RET_ALLOC_X(var, code) do {if (!var) RET_ERR_X ("failed to allocate " #var, code); \
+#define RET_NULL_X(var, code) do {if (!var) {RET_ERR_X(#var " is null", code);}} while (0)
+#define RET_ALLOC_X(var, code) do {if (!var) {RET_ERR_X("failed to allocate " #var, code);} \
@@ -2574 +2574 @@
-      looking_for_services](const dds_builtintopic_endpoint_t & sample, std::string & topic_name,
+    looking_for_services](const …
```
> Address CMake and uncrustify linter violations

- rmw_cyclonedds_cpp/src/rmw_node.cpp
There are some return value errors in CI test of rcl and rclaction, like [this](http://build.ros2.org/job/Eci__nightly-cyclonedds_ubuntu_bionic_amd64/41/testReport/rcl/TestGraphFixture__rmw_cyclonedds_cpp/test_rcl_get_publisher_names_and_types_by_node/).
I think we should have the return value `RMW_RET_NODE_NAME_NON_EXISTENT` if we can't get the node.
Signed-off-by: evshary <evshary@gmail.com>
> Return NODE_NAME_NON_EXISTENT instead of ERROR.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
PR #44 unintentionally introduced a compatibility issue with Dashing and older by switching to the newly introduced ``NODE_NAME_NON_EXISTENT`` error code. For Dashing and older, we need to continue using the generic ``ERROR``. Fortunately they're macros, so a single source base remains possible.
> Use RMW_RET_NODE_NAME_NON_EXISTENT only if defined

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdes.hpp
> Remove dead string serialization code

- rmw_cyclonedds_cpp/CMakeLists.txt
- rmw_cyclonedds_cpp/src/rmw_node.cpp
Includes changes in #46, in a way that makes it work both before and after https://github.com/ros2/rmw/pull/187
> Compatibility before and after RMW pub/sub option structures

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Looks like a copy-paste mistake
> Use right event info for RMW_EVENT_LIVELINESS_LOST

- rmw_cyclonedds_cpp/src/rmw_node.cpp
addresses the missing functions for zero-copy API as noted in here: https://github.com/ros2/ros2/issues/785#issuecomment-544337245
Connects to https://github.com/ros2/rclcpp/pull/896
Signed-off-by: Karsten Knese <karsten@openrobotics.org>
> zero copy api for cyclonedds

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This PR removes the functions previously merged in https://github.com/ros2/rmw_cyclonedds/pull/53 to comply with the current master. This PR is then in line with https://github.com/ros2/rclcpp/pull/896 and should be merged with the connecting ones.
Signed-off-by: Karsten Knese <karsten@openrobotics.org>
> rename return functions

- rmw_cyclonedds_cpp/src/rmw_node.cpp
GCC and Clang support the ternary operator in macros, MSVC does not.
> Make RMW version acceptable to MSVC

- rmw_cyclonedds_cpp/src/rmw_node.cpp
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8567)](http://ci.ros2.org/job/ci_linux/8567/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4442)](http://ci.ros2.org/job/ci_linux-aarch64/4442/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6988)](http://ci.ros2.org/job/ci_osx/6988/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8485)](http://ci.ros2.org/job/ci_windows/8485/) <- Expected Failure
> Suppress a syntax error identified by cppcheck 1.89

- rmw_cyclonedds_cpp/src/rmw_node.cpp
@dirk-thomas there's this:
https://github.com/ros2/rcutils/blob/540d9472b0c7de4b029f2e26f3388e3b9a5bb1eb/include/rcutils/get_env.h#L52
There is no way of knowing who will be calling ``rcutils_get_env`` or when, so I think this limitation is asking for trouble. I presume this has been considered in the past and deemed acceptable, and if so (and assuming my change gets through review and test build) feel free to simply merge it.
> Use rcutils_get_env() instead of getenv() (#71)

- rmw_cyclonedds_cpp/src/Serialization.cpp
- rmw_cyclonedds_cpp/src/Serialization.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
- rmw_cyclonedds_cpp/src/serdata.hpp
Also make serdata a private header
Reduces overall latency on ApexAI benchmark by about 10%
> Serialize into uninitialized memory, not vector

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/exception.hpp
- rmw_cyclonedds_cpp/src/Serialization.cpp
- rmw_cyclonedds_cpp/src/TypeSupport2.cpp
- rmw_cyclonedds_cpp/src/TypeSupport2.hpp
- rmw_cyclonedds_cpp/src/bytewise.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
- rmw_cyclonedds_cpp/src/serdata.hpp
Introduce a new `[[noreturn]] unreachable()` function that marks code as unreachable and throws a logic error if it is executed.
Fix build error due to Windows min/max macros.
Fix linker errors from referring to a non-constexpr extern from a constexpr.
Fix warnings about narrowing conversions.
> Mark code that should be unreachable

- rmw_cyclonedds_cpp/src/Serialization.cpp
- rmw_cyclonedds_cpp/src/Serialization.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
- rmw_cyclonedds_cpp/src/serdata.hpp
1. Make CDRWriter remember its top level struct value type
2. Populate the trivially serializable cache when CDRWriter is created instead of waiting until the first time a message is sent.
> Cache serialization info when CDRWriter is constructed

- rmw_cyclonedds_cpp/CMakeLists.txt
- rmw_cyclonedds_cpp/src/rmw_get_topic_endpoint_info.cpp
- rmw_cyclonedds_cpp/src/rmw_get_topic_info.cpp
**NOTE: DO NOT MERGE until https://github.com/ros2/rmw/pull/186 and https://github.com/ros2/rmw_implementation/pull/72 are merged.**
Leaving stubs for `rmw_get_publishers_info_by_topic()` and `rmw_get_subscriptions_info_by_topic()`.
Related to [aws-roadmap#94](https://app.zenhub.com/workspaces/aws-robotics-open-source-roadmap-5d9662bf4e1ec400011c53c6/issues/ros-security/aws-roadmap/94).
> Stubs for rmw_get_publishers_info_by_topic and rmw_get_subscriptions_info_by_topic

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Code correctness only. No noticeable effects expected.
> dds_time_t instead of dds_duration_t for absolute time

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/rmw_version_test.hpp
- rmw_cyclonedds_cpp/src/rmw_get_topic_endpoint_info.cpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
... and this PR avoids trying to compile them on Dashing, similarly to how other RMW interface changes have been dealt with in the Cyclone DDS RMW layer so far.
> rmw_get_topic_endpoint_info doesn't exist on Dashing

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This PR adds support for events in `rmw_wait`, which is required for the lifespan and deadline qos to work properly. I've also added code for setting the deadline, lifespan and liveliness qos policies in `create_readwrite_qos`. And when getting qos properties in `get_readwrite_qos`, an infinite duration is no longer returned as 0, as `test_get_actual_qos__rmw_cyclonedds_cpp` expects the value to be >= MAX_INT32
> Support for deadline, lifespan and liveliness qos

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp
- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/serdes.hpp
- rmw_cyclonedds_cpp/src/TypeSupport2.cpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.
> code style only: wrap after open parenthesis if not in one line

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Add version check >= 0.8.2 to fix ros2 dashing builds; types rmw_topic_endpoint_info_t and rmw_topic_endpoint_info_array_t don't exist in dashing.
> Fix dashing builds wrt rmw_topic_endpoint_info_t

- rmw_cyclonedds_cpp/src/serdata.cpp
Closes #90 
Closes https://github.com/ros-tooling/aws-oncall/issues/66
Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>
> Fix MSBuild warnings C4146 and C4267

- rmw_cyclonedds_cpp/src/serdata.cpp
Corrects recent build warnings in CI (for example https://ci.ros2.org/view/packaging/job/packaging_windows/1648/), because `std::hash` returns a `size_t`
```
serdata.cpp:468, MSBuild, Priority: Normal
--
'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
```
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Correct std::hash return type sizes

- rmw_cyclonedds_cpp/src/rmw_node.cpp
The other rmw implementations currently return all node names, even if there are duplicates. This behavior allows us to reason about there being duplicate nodes in the system and warn the user about it, even if we can't solve it. Using the `std::set` only masks this potentially confusing case.
Unblocks https://github.com/ros2/ros2cli/pull/463
Related to https://github.com/ros2/ros2cli/issues/453
Related to https://github.com/ros-tooling/aws-roadmap/issues/196
Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>
> Use a list instead of a set for node names list

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Related to https://github.com/ros2/ros2/issues/822
This adds the `rmw_publisher_event_init()` and `rmw_subscription_event_init()` functions to `rmw_cyclonedds`, moved from `rmw`, so that these functions will be able to check for whether or not the given type of `rmw_event_type_t` is supported by the chosen middleware.
> Add rmw_*_event_init() functions

- rmw_cyclonedds_cpp/src/TypeSupport2.hpp
Since m_get_const_function calls `std::vector<T>::operator[]`, accessing the zeroth element causes undefined behavior. Instead, return a null pointer to make the function behave sanely when vector is empty.
Fix #120
> Prevent undefined behavior when serializing empty vector

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Related to [this](https://github.com/ros2/ros2/issues/822) feature request. The design and implementation details can also be found there.
Handling events of type `REQUESTED_INCOMPATIBLE_QOS_STATUS` and `OFFERED_INCOMPATIBLE_QOS_STATUS`
> Support for ON_REQUESTED_INCOMPATIBLE_QOS and ON_OFFERED_INCOMPATIBLE_QOS events

- rmw_cyclonedds_cpp/src/rmw_node.cpp
The absence of compile-time guards breaks Dashing & Eloquent builds since #125 got merged.
> Include incompatible_qos_events_statuses.h only on Foxy (and newer)

- .github/workflows/CI.yml
Especially since we maintain compatibility across multiple ROS versions, which new contributors might not expect, this should help prevent accidental build-breaking.
> Add CI with GitHub actions

- .github/workflows/CI.yml
Binary builds build silently on non-Linux platforms, so we previously weren't *actually* testing Eloquent and Dashing on Windows and Mac.
> In CI, always build ROS from source

- .github/workflows/CI.yml
By changing the matrix, we make the job names cleaner
Before:
After:
> Better CI job names

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Needed since https://github.com/ros2/rmw/pull/189.
> API changes to sync with one Participant per Context change in rmw_fastrtps

- README.md
- rmw_cyclonedds_cpp/src/rmw_node.cpp
Add utility function to insert security settings to the cyclone QOS object used to create nodes. Include a utility to find security files and properly format their location to use with DDS.
Code testing included running the ROS2 tutorials with encryption enabled, error checking for missing certificates, testing bad signatures on governance and permissions files, invalid or mismatched domain IDs, and invalid encryption keys.
> Enable use of Cyclone DDS security features

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport.hpp
- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp
- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/macros.hpp
- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/u16string.hpp
- rmw_cyclonedds_cpp/src/Serialization.hpp
- rmw_cyclonedds_cpp/src/TypeSupport2.hpp
- rmw_cyclonedds_cpp/src/u16string.cpp
> rename rosidl_generator_c namespace to rosidl_runtime_c

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>
> security-context -> enclave

- rmw_cyclonedds_cpp/src/rmw_node.cpp
The existing `rmw_set_log_severity` currently just throws an error. This implements it.
> Implement rmw_set_log_severity

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp
Splits the `align_` function and overloads it avoids an unnecessary cast from `size_t` to `void *`.
Avoids passing the casted pointer by reference.  In the existing `align_` function, the pointer argument is both manipulated via reference and returned, which is both confusing and potentially dangerous, since it's behaviour is not clear from the function prototype.
> implement safer align_ function

- rmw_cyclonedds_cpp/src/fallthrough_macro.hpp
The current fallthrough macro gave me a warning now on OSX when compiling with `-Werror`:
```
error: use of the 'fallthrough' attribute is a C++17 extension [-Werror,-Wc++17-extensions]
FALLTHROUGH;
```
The reason, as far as I can tell, is that the compiler is c++17 enabled, yet we're compiling the project with a C++14 standard. 
Also I think there was a typo when choosing the compiler version for 17, according to
https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html
> 201703L for the 2017 C++ standard 
EDIT: ~Looking into a default behavior for gcc7, I found this: https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/ and applied the `__attribute__  ((fallthrough))`~
As to be expected, MSVC doesn't know that attribute. Going back to comment as default …
> correct fallthrough macro

- rmw_cyclonedds_cpp/src/Serialization.cpp
Serialization issue reported in https://github.com/eclipse-cyclonedds/cyclonedds/issues/488
> Fix serialization on non-32-bit, big-endian systems

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Fixes https://github.com/ros2/rmw_cyclonedds/pull/145#issuecomment-617996341.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10401)](http://ci.ros2.org/job/ci_linux/10401/)
> Fix build warnings

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This fills the timestamps in the message_info.
> Fill in message_info timestamps

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Implementation of ros2/rmw#212.
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Add support for taking a sequence of messages

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This pull request aims to fix [a warning seen on nightly Windows builds](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1533/msbuild/category.63474818/). Said warning was introduced in https://github.com/ros2/rmw_cyclonedds/pull/148. This was first observed when running CI for [ros2/launch#408](https://github.com/ros2/launch/pull/408#issuecomment-620162001). 
CI up to `rmw_connext` and `rmw_cyclonedds_cpp`:
- Windows [![Build Status](https://ci.ros2.org/job/ci_windows/10425/badge/icon)](https://ci.ros2.org/job/ci_windows/10425/)
> Cast size_t to uint32_t explicitly.

- .github/resources/suppress_other_rmw.repos
- .github/workflows/CI.yml
Since #145, the CI build of rmw_cyclonedds_cpp has been failing on Windows due to inadvertently injecting fastrtps into the build process.
fastrtps fails to build (https://github.com/eProsima/Fast-RTPS/issues/1173) causing the CI to fail.
There doesn't seem to be a better way to suppress this in action-ros-ci https://github.com/ros-tooling/action-ros-ci/issues/177
Fixes #164
> Exclude other RMW from Github CI build

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Only generate the error "Recompile with '-DENABLESECURITY=ON' error when not compiled with security and the environment variable ROS_SECURITY_STRATEGY="Enforce". Addresses https://github.com/ros2/rmw_cyclonedds/pull/123#discussion_r416883418 and https://github.com/ros2/rmw_cyclonedds/pull/172#discussion_r416892363.
Signed-off-by: Sid Faber <sid.faber@canonical.com>
> Address error message

- rmw_cyclonedds_cpp/src/rmw_node.cpp
The same approach was used in `rmw_fastrtps`.
Fixes https://github.com/ros2/rmw_cyclonedds/issues/174.
> Initialize participant on first use. Destroy participant after last node is destroyed.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Fixes https://github.com/ros2/system_tests/pull/428.
> Fix topic name mangling when not using ros conventions

- .github/workflows/CI.yml
Master has build-fixing changes for compatibility with the GitHub Windows runner since https://github.com/ros-tooling/setup-ros/pull/159
> CI: switch setup-ros to master

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp
avoids unnecessary casts to pointer and pointer manipulation by reference.
this is the same as PR #141, which was previously merged into `master`, but way ahead of the `dashing-eloquent` fork.
> implement safer align function

- rmw_cyclonedds_cpp/src/Serialization.cpp
Serialization issue reported in [eclipse-cyclonedds/cyclonedds#488](https://github.com/eclipse-cyclonedds/cyclonedds/issues/488).
This same patch was merged with `master` in PR #159.
Discussion about merging with `dashing-eloquent` in Issue #188.
> fix serialisation on 64-bit, big-endian systems: dashing-eloquent

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This "mostly fixes" the lost service responses (#183, #74) by reinstating the check for a matching reader and writer in `rmw_service_server_is_available` that was accidentally deleted when the 1:1 mapping of nodes to participants was replaced by a 1:1 mapping of contexts to participants. This effectively restores dashing/eloquent behaviour.
It doesn't truly fix the problem and in the presence of packet loss the likelihood of failure remains significant. However, the workaround proposed in #187 is a bit controversial and this restoration of the old code at least should be non-controversial.
> Restore dashing/eloquent behaviour of "service_is_available"

- rmw_cyclonedds_cpp/src/graphrhc.cpp
The RMW layer in dashing/eloquent depends on a still-evolving interface for custom reader history caches in Cyclone. https://github.com/eclipse-cyclonedds/cyclonedds/pull/499 extends that interface, this PR ensures the sources in the RMW layer will be compatible with Cyclone also after merging that PR.
I believe future proofing by a change of this nature makes sense anyway, but a mishap in implementing #142 means dashing today still relies on cyclonedds' master branch (it is a good thing Cyclone DDS regressions are pretty rare!). Therefore, https://github.com/eclipse-cyclonedds/cyclonedds/pull/499 can only go into Cyclone after either this PR, or https://github.com/ros2/ros2/pull/907 or both have been merged.
Note that Eloquent and Foxy are "safe": Eloquent because it uses …
> Provide a dummy readcdr function if needed

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Precisely what the title says. Connected to https://github.com/ros2/rcl/pull/689.
> Handle RMW_DEFAULT_DOMAIN_ID.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This pull request ensures `rmw_context_fini()` fails on a not shutdown context, as its API contract establishes (see https://github.com/ros2/rmw/pull/242).
> Finalize context if and only if it's shutdown

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Complying with https://github.com/ros2/rmw/pull/244.
> Ensure compliant init options API implementations.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Connected to https://github.com/ros2/rmw/pull/247.
> Amend rmw_init() implementation: require enclave.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Connected to https://github.com/ros2/rmw/pull/249.
> Ensure compliant node construction/destruction API.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Backport #187 to Foxy.
I believe since this is only touching a cpp file that the change is ABI compatible.
I will confirm that the change is also wire compatible, to be sure.
> [foxy backport] Lost service responses (#183, #74) (#187)

- rmw_cyclonedds_cpp/src/rmw_node.cpp
See https://github.com/ros2/rcl/pull/718.
> Set context actual domain id

- .github/workflows/CI.yml
- README.md
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
For the proper use of "ROS 2" :grin:
I modified more than just the README, hope you don't mind.
Also, if someone could fix the repo description, that would be nice
> **ROS2** RMW layer for Eclipse Cyclone DDS
> Add space between 'ROS' and '2'

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This fixes #211 by fixing an embarrassing copy-paste mistake.
> rmw_destroy_node must remove node from graph cache

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Precisely what the title says. Connected to ros2/rmw#252.
> Ensure compliant publisher API

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Depends on https://github.com/ros2/rmw/pull/256.
> Ensure compliant subscription API.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
A tiny fix, to make sure `ret` actually gets `rmw_serialized_message_resize()` return value.
> Fix bad conditional in rmw_serialize().

- .github/workflows/CI.yml
Bring CI up to date and add Ubuntu 20.04, the current target platform for ROS Rolling.
> Bump CI version

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Related to ros2/rcl#721
<details><summary>memory leak log</summary>
<p>
```shell
==23528== 29 bytes in 1 blocks are definitely lost in loss record 1 of 72
==23528==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23528==    by 0x1DAA6A: void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) (basic_string.tcc:219)
==23528==    by 0x5D45786: cycdeser::deserialize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (serdes.hpp:165)
==23528==    by 0x5D450F4: cycdeser::operator>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (serdes.hpp:113)
==23528==    by …
```
> Fix memory leak that string not deleted.

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport.hpp
- rmw_cyclonedds_cpp/src/serdata.cpp
Related to ros2/rcl#721
<details><summary>memory leak log</summary>
<p>
```shell
==23528== 92 (40 direct, 52 indirect) bytes in 1 blocks are definitely lost in loss record 38 of 72
==23528==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23528==    by 0x5D9668B: create_message_type_support(void const*, char const*) (serdata.cpp:84)
==23528==    by 0x5D379CF: create_cdds_publisher(int, int, rosidl_message_type_support_t const*, char const*, rmw_qos_profile_t const*) (rmw_node.cpp:1839)
==23528==    by 0x5D37E25: create_publisher(int, int, rosidl_message_type_support_t const*, char const*, rmw_qos_profile_t const*, rmw_publisher_options_t const*) (rmw_node.cpp:1910)
==23528==    by 0x5D34221: …
```
> Fix memory leak that type support not deleted.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Precisely what the title says. Otherwise, SIGSEGV ensues if a subsequent (re)initialization fails halfway through.
> Fix context impl cleanup.

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport.hpp
- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
This PR is related to https://github.com/ros2/rmw_cyclonedds/issues/219
NOTE: I used multiple commits in a PR because it'll easy for me to revert some of them if they're unnecessary.
Signed-off-by: Chen.Lihui <lihui.chen@sony.com>
> Use correct functions to resize and get an item, avoiding memory leaks in typesupport code

- .github/resources/local.repos
- .github/workflows/CI.yml
Fixes #220
Fast forward to https://github.com/ament/ament_lint/pull/268
This suppresses a defect in `ament_cppcheck` - namely that if a macro is missing at checking time, it fails loudly. This is compounded by fact that `ament_cppcheck` does not include all dependent headers, so macros are likely to be missing.
> Suppress cppcheck unknownMacro

- rmw_cyclonedds_cpp/src/rmw_node.cpp
> Updated error returns on rmw_publish to comply with documentation

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Fixes #235
Signed-off-by: Chen.Lihui <lihui.chen@sony.com>
> Fix that not to delete some objects after destroying functions

- rmw_cyclonedds_cpp/src/rmw_node.cpp
> Updated error returns on rmw_take_serialized and with_message_info

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Fix for regression introduced in #241. See https://ci.ros2.org/job/ci_linux/12374/testReport/.
Full CI (expensive, but just to be sure):
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12385)](http://ci.ros2.org/job/ci_linux/12385/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7353)](http://ci.ros2.org/job/ci_linux-aarch64/7353/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10096)](http://ci.ros2.org/job/ci_osx/10096/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12297)](http://ci.ros2.org/job/ci_windows/12297/)
> Check for message_info on take where appropriate.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Connected to https://github.com/ros2/rmw/pull/272. This patch affects:
- `rmw_get_node_names()`
- `rmw_get_node_names_with_enclaves()`
- `rmw_get_topic_names_and_types()`
- `rmw_get_service_names_and_types()`
- `rmw_get_publishers_info_by_topic()`
- `rmw_get_subscriptions_info_by_topic()`
- `rmw_get_subscriber_names_and_types_by_node()`
- `rmw_get_publisher_names_and_types_by_node()`
- `rmw_get_service_names_and_types_by_node()`
- `rmw_get_client_names_and_types_by_node()`
- `rmw_count_publishers()`
- `rmw_count_subscribers()`
> Update graph API return codes.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
To be compliant with the API spec. Connected to https://github.com/ros2/rmw/pull/274.
> Update gid API return codes.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Connected to https://github.com/ros2/rmw/pull/276. Precisely what the title says.
> Update service/client construction/destruction API return codes.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Updated return codes for unimplemented rmw_*_*_allocation functions. Related with this PR https://github.com/ros2/rmw_implementation/pull/137
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Updated rmw_* return codes

- rmw_cyclonedds_cpp/src/rmw_node.cpp
> Update service/client request/response API error returns

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Return the right error code. Related with https://github.com/ros2/rmw/pull/281
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Return RMW_RET_UNSUPPORTED in rmw_get_serialized_message_size

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Using %ld to print a std::size_t leads to compiler warnings and will lead
to wrong behavior whenever the specific std::size_t is bigger than LONG_MAX
> Change wrong use of %ld to print std::size_t to %zu

- .github/resources/local.repos
- .github/workflows/CI.yml
- rmw_cyclonedds_cpp/src/rmw_node.cpp
This PR depends on: 
- https://github.com/ros2/rcpputils/pull/103
Included error checks, return the right code errors, avoid crashes, etc
> [Backport Foxy] Included improvements to increase code coverage

- rmw_cyclonedds_cpp/src/demangle.cpp
This PR is intended to correct incorrect log messages.
I checked that the log message was wrong and changed it.
(rmw_fastrtps_shared_cpp -> rmw_cyclonedds_cpp)
> fix incorrect log message(rmw_fastrtps_shared_cpp -> rmw_cylonedds_cpp)

- rmw_cyclonedds_cpp/src/Serialization.cpp
Since `get_cdr_alignof_primitive` can potentially return 0 if `v.type_kind()` is not a primitive type, clang static analysis flags this `if` branch as having potentially undefined behavior.
I wasn't entirely sure what to do here. I could use an `assert(cdr_alignof != 0)` since this is situation is not supposed to occur, but returning false also seemed like a decent solution.
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Handle potential divide by 0

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Follow-up after https://github.com/ros2/rosidl_typesupport/pull/99. Missing error handling code caused test failures in downstream packages (e.g. https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_release/1415/). This patch addresses them.
Full CI (just in case):
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13273)](http://ci.ros2.org/job/ci_linux/13273/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8205)](http://ci.ros2.org/job/ci_linux-aarch64/8205/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10993)](http://ci.ros2.org/job/ci_osx/10993/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13304)](http://ci.ros2.org/job/ci_windows/ …
> Handle typesupport errors on fetch.

- rmw_cyclonedds_cpp/src/TypeSupport2.cpp
The individual commits have more information, but essentially make sure to reset the error in between calls to probing for typesupport.  This should fix the bulk of the test failures we are seeing in https://github.com/ros2/rmw/pull/293 .
@eboasson Note that this is different than what we had discussed earlier.  After talking to some more people, changing the contract of [get_typesupport_handle_function](https://github.com/ros2/rosidl_typesupport/blob/64dd1be918b759f0a2d0c731ebe38ccbbe4601b4/rosidl_typesupport_cpp/src/type_support_dispatch.hpp#L37) is a little more dangerous than we want to attempt right now .  So this is the more targeted, if less ideal, solution.  I'll likely still open an issue to follow-up and change that contract, since the current contract seems a bit ugly.
CI for …
> Reset the error on failing to find the C typesupport

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Otherwise global destructor ordering can result in the global state being
destroyed before the last use.  Not cleaning up does cause a small memory leak
at shutdown, but it is limited to an empty map of domains and an empty
unordered set of waitsets.
> Use init-on-first-use for global state

- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
- rmw_cyclonedds_cpp/src/serdata.hpp
Cyclone DDS is about to get type discovery in eclipse-cyclonedds/cyclonedds#559 and the evolving interface for custom message representation/serialisation will change a little bit as a consequence. That PR does provide ABI compatibility, so an old `rmw_cyclonedds_cpp` binary will still work fine (if slightly slower), eliminating one risk in upgrading binary packages. (Source compatibility could have been provided but I decided against that because the benefit is just too marginal, and it isn't an official stable API yet anyway.)
The first commit in this PR updates the interface and uses the C preprocessor to also support building against a version of Cyclone DDS that hasn't got the type discovery merged in yet. It is fairly big because it consistently updates all places where it really …
> Compatibility with Cyclone DDS type discovery

- rmw_cyclonedds_cpp/src/rmw_node.cpp
The reference to the sertype is not counted and shouldn't be released.
At this point, and in this test anyway, the memory has been freed just
before (by `dds_delete(topic)`) and this probably explains why it hasn't
caused any breakage before.  The assert that failed now is new in
Cyclone.
There has been an ancient interface for creating custom types that did
require it and that was used by `rmw_cyclonedds_cpp` in the past.  The
rewrite of the RMW layer to use one DDS participant per context
(commit 8a1d3fc092d1d4841c9f5c39e7da0e3b26886add) also dropped support
for that ancient interface.  Instead of removing the #if/unref/#endif,
that commit removed the #if/#endif but left the unref call in place.
This fixes #277
> Fix use-after-free in error handling bug

- .github/resources/local.repos
- .github/workflows/CI.yml
Workflows started to fail after https://github.com/ament/ament_lint/pull/268 was merged, e.g.: https://github.com/ros2/rmw_cyclonedds/pull/288.
This should fix it :crossed_fingers:
> Fix github workflows

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Depends on https://github.com/ros2/rmw/pull/301
Alternative to https://github.com/ros2/rmw_cyclonedds/pull/287
Meets the new API expectations introduced in https://github.com/ros2/rmw/pull/301 - to accept and return `RMW_DURATION_INFINITE` for cross-implementation consistency.
> Take and return new RMW_DURATION_INFINITE correctly

- rmw_cyclonedds_cpp/CMakeLists.txt
- rmw_cyclonedds_cpp/src/TypeSupport.cpp
- rmw_cyclonedds_cpp/src/TypeSupport.hpp
- rmw_cyclonedds_cpp/src/TypeSupport_impl.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
- rmw_cyclonedds_cpp/src/serdata.hpp
This PR adds support for the zero-copy API.
> Add loaned sample zero-copy API support

- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.hpp
This PR updates to use the macros directly from Cyclone DDS to work with the payload sample when using SHM
> Fix compiler warnings with Iceoryx

- rmw_cyclonedds_cpp/src/rmw_node.cpp
The comment in the code explains it in a lot more detail, but
essentially this avoids a signed/unsigned mismatch in higher
level code.  Since the depth is meaningless in KEEP_ALL anyway,
this shouldn't have any deleterious effects elsewhere.
Originally from Erik Boasson (@eboasson).
This should fix https://github.com/ros2/ros2cli/issues/603
> Fix the history depth for KEEP_ALL.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
https://github.com/ros2/rcutils/pull/340 deprecates `rcutils/get_env.h`. This PR doesn't need to wait until the `rcutils` PR is merged, though.
> Update includes after rcutils/get_env.h deprecation

- .github/resources/local.repos
- .github/workflows/CI.yml
There's no real reason to have it. It's not officially supported for Rolling.
Also, ignore `rmw_connextdds` in CI (just like `rmw_connext`). Note that if you want to keep the `ubuntu-18.04` job, this might fix it.
Finally, I bumped `action-ros-ci` to `v0.2`. This fixes the issue for Windows, although there seems to be another issue. Still an improvement though!
> Remove ubuntu-18.04 job from CI config matrix and ignore rmw_connextdds

- README.md
> Change index.ros.org -> docs.ros.org links.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
> Add rmw_publisher_wait_for_all_acked support

- shared_memory_support.md
Signed-off-by: Matthias Killat <matthias.killat@apex.ai>
Add a brief description how to enable shared memory support. The purpose is to enable a ROS2 user to activate the Shared Memory feature in her applications when using rmw_cyclonedds. 
Unfortunately there is no (simple) example yet in the ROS default examples where Shared Memory is actually used (at least none that I am aware of). However, it is fairly straightforward how the talker and listener example needs to be adapted to demonstrate use of shared memory support (essentially just use a fixed size data type, i.e. not a string). This is briefly sketched as well as a list of current restrictions.
Most of the important restrictions should be covered but some of them might change slightly (e.g. QoS requirements) and the document will …
> Added shared memory support usage description

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This gets rid of a bunch of custom code in rmw_cyclonedds_cpp.
This requires https://github.com/ros2/rmw_dds_common/pull/51 to go in first.
> Use the new rmw_dds_common::get_security_files API.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
If the rmw_dds_common layer tells us that the CRL exists,
set the appropriate property so CycloneDDS will honor it.
Note that this can be merged at any time, but will have no effect until https://github.com/ros2/rmw_dds_common/pull/52 is merged.
> Pass the CRL down to CycloneDDS if it exists.

- rmw_cyclonedds_cpp/CMakeLists.txt
- rmw_cyclonedds_cpp/package.xml
- rmw_cyclonedds_cpp/src/rmw_node.cpp
This adds tracing instrumentation for publisher/subscription initialization at the `rmw` level. By recording the pub/sub GIDs, we can match ROS 2 pubs/subs with the corresponding DDS writers/readers. For example, with Cyclone DDS: https://github.com/eclipse-cyclonedds/cyclonedds/pull/898
This also adds a tracepoint for `rmw_publish` and `rmw_take` so that we can track published/taken messages at the `rmw` level.
Requires https://gitlab.com/ros-tracing/ros2_tracing/-/merge_requests/254
action-ros-ci-repos-override: https://gist.githubusercontent.com/christophebedard/a83485b0bdea8458e61d59ed5668e27f/raw/2cb93590b8e18e6cb976408610f864acb47d1021/ros2.repos
action-ros-ci-repos-override: https://raw.githubusercontent.com/ros2/rmw_cyclonedds/master/.github/resources/local.repos
Signed-off-by: …
> Add pub/sub init, publish and take instrumentation using tracetools

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This fixes a build warning when updating cyclone to `releases/0.8.x` and depends on ros2/ros2#1174
> Fix use of deprecated is_loan_available

- README.md
- rmw_cyclonedds_cpp/QUALITY_DECLARATION.md
Closes #331
Looks like the current state of the package corresponds to QL 4.
It's technically supposed to be QL 1 for downstream packages (rcl, rclcpp, rclpy) to be QL 1, but some of the missing items are quite trivial (bumping to 1.0.0, creating missing upstream QDs).
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
> Add quality declaration for rmw_cyclonedds_cpp

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Since rmw_allocate() was used to allocate memory, we should use rmw_free() to cleanup.
Otherwise, if the user provided a custom allocator to the context we will be calling deallocate with the wrong allocator.
---
I hit a runtime error due to this bug while I was using a custom allocator.
There may be other places in the code where we're making a similar mistake. I haven't audited the rest of the code, but I'll make sure to fix similar instances if I come across them.
This should be considered for backport to Galactic and Foxy!
> Free with the same allocator in rmw_destroy_node

- rmw_cyclonedds_cpp/CMakeLists.txt
Part of ament/ament_cmake#365
This makes rmw_cyclonedds_cpp export modern CMake targets. Currently it only makes old-style standard variables available.
> Export modern CMake targets

- rmw_cyclonedds_cpp/CMakeLists.txt
Required for ros2/rmw_implementation#201 which fixes a rolling CI job failure caused by ros2/rmw_cyclonedds#357
Since this is an rmw implementation, it's implementing the `rmw` API. I think `rmw::rmw` is the only target that needs to be marked `PUBLIC`. The rest downstream targets don't need to know about, and exporting them causes failures when the targets are from packages that don't get `find_package()`'d, notably with [`tracetools::tracetools`.](http://ci.ros2.org/job/ci_linux-aarch64/10464/).
> Export only rmw::rmw to downstream targets

- rmw_cyclonedds_cpp/CMakeLists.txt
- rmw_cyclonedds_cpp/package.xml
- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
- rmw_cyclonedds_cpp/src/serdata.hpp
> Fix freeing of loaned chunks 

- rmw_cyclonedds_cpp/src/rmw_node.cpp
A call to dissociate_writer, like it did before, is a no-op.  The result
is that the ros_discovery_info topic sample keeps growing when one
creates and destroy subscriptions in the application.
> Call dissociate_reader in rmw_destroy_subscription

- README.md
- rmw_cyclonedds_cpp/QUALITY_DECLARATION.md
And therefore requirement 5.i is fulfilled.
I also noticed that 1.ii can also be marked as done, so this results in a bump to QL2. This can't be bumped to QL1 because [`rmw_dds_common`'s QL1 requires a QL1 middleware](https://github.com/ros2/rmw_dds_common/blob/master/rmw_dds_common/QUALITY_DECLARATION.md#rmw_dds_common-quality-declaration). If `cyclonedds` is bumped from QL2 to QL1, then I think `rmw_cyclonedds_cpp` can also be bumped to QL1.
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
> Bump QDs to QL2

- rmw_cyclonedds_cpp/src/rmw_node.cpp
When building on Ubuntu 22.04 in Release mode, gcc complains that:
‘stact’ may be used uninitialized in this function [-Wmaybe-uninitialized] 2295
I think this is probably a false positive; in any situations
where stact was not set, we would have gotten out before this.
Regardless, just set stact to nullptr, which quiets the warning
and should have no deleterious effects.
This should fix warnings from the nightlies like the last one shown in https://ci.ros2.org/view/nightly/job/nightly_linux_release/2205/gcc/new/
> Fix a warning by making a pointer nullptr.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdata.cpp
Adding bug-fixes to rmw_cyclonedds:
- additional checks for `borrow_loaned_message_int` to make sure that no nullptr is passed or when a message is already loaned
- adding serialization in `serdata_rmw_to_sample` when `is_request_header = false` to work with server/client API
@eboasson @MatthiasKillat @sumanth-nirmal 
Would you take a look on this? ~~The PR is currently in Draft state because there is another issue with the node graph that needs investigation.~~
> Fix for shared memory transport tests

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Determining whether a service is available relies on topic names, but
the function to retrieve a topic name mishandled long names by accepting
a truncated name when the 128-byte buffer passed in was too small
instead of retrying with a larger buffer.
Cyclone DDS' underlying function always returns the actual length of the
name and topic names can't change, and so there is no need to guess or
loop.
Fixes #384
> Fix get_topic_name and handling long service names

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Connects to: https://github.com/ros2/rmw/pull/320
Twin of: https://github.com/ros2/rmw_fastrtps/pull/598
If users set certain QoS policies to BEST_AVAILABLE, then we query the graph for endpoint info. The policy is updated such that it is compatible with all endpoints while maintaining the highest possible level of service.
> Handle 'best_available' QoS policies

- rmw_cyclonedds_cpp/src/Serialization.cpp
This is needed for memset() and memcpy().
This should fix #392
> Add cstring include.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This builds on #233 by also fixing the %d bit.
> Fix format string incorrect use of %ld/%d instead of %zu/%PRIu32

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This improves the error message when creating a topic fails. The return codes are the documented return codes for `dds_create_topic_generic` and `dds_create_topic_sertype`, which is what `create_topic()` uses depending on the preprocessor definition `DDS_HAS_DDSI_SERTYPE`.
https://cyclonedds.io/docs/cyclonedds/latest/api/topic.html#c.dds_create_topic_generic
https://cyclonedds.io/docs/cyclonedds/latest/api/topic.html#c.dds_create_topic_sertype
> Improve error message when create_topic fails

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This PR addresses the issue #409. As the title states, it adds the topic name to the error message when create_topic fails.
Signed-off-by: Voldivh <eloyabmfcv@gmail.com>
> Adds topic name to error msg when create_topic fails

- rmw_cyclonedds_cpp/include/rmw_cyclonedds_cpp/TypeSupport_impl.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
Backport #313 to Foxy.
This fixes a test failure that cropped up with https://github.com/ros2/rosidl/pull/604
CI together with the connected PR:
- Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17294)](https://ci.ros2.org/job/ci_linux/17294/)
- Linux-aarch64 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11835)](https://ci.ros2.org/job/ci_linux-aarch64/11835/)
- Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17781)](https://ci.ros2.org/job/ci_windows/17781/)
> [foxy] Handle allocation errors during message deserialization (#313)

- rmw_cyclonedds_cpp/src/rmw_node.cpp
argument check as rmw interface implementation. (this never happens if called from rcl, since rcl does this NULL check.)
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
> add NULL check before accessing object.

- rmw_cyclonedds_cpp/CMakeLists.txt
This fixes a build failure in downstream packages when building with `-DBUILD_SHARED_LIBS=OFF`. The exported `rmw_cyclonedds` CMake target references `$<LINK_ONLY:CylconeDDS:ddsc>`, but `CycloneDDS` hasn't been `find_package()`'d downstream so the target doesn't exist. This PR fixes that.
> Export CycloneDDS dependency

- rmw_cyclonedds_cpp/src/TypeSupport_impl.hpp
- rmw_cyclonedds_cpp/src/rmw_node.cpp
Backport #313 to Galactic.
I think this fixes the same test failure that the original PR was fixing for Humble and newer.
> [galactic] Handle allocation errors during message deserialization (#313)

- rmw_cyclonedds_cpp/src/rmw_node.cpp
That way it is an actual C/C++ statement, and we can make minor changes to that macro as needed.
On its own, this isn't interesting, but I'm going to be doing some minor modifications to the `RMW_CHECK_TYPE_IDENTIFIERS_MATCH` macro that requires this.
> Make sure to add semicolons to the CHECK_TYPE_IDENTIFIER_MATCH.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Note that this is not hooked up inside of CycloneDDS, so this will never fire currently.
Part of https://github.com/ros2/ros2/issues/1361
Depends on https://github.com/ros2/rmw/pull/339
> Implement inconsistent topic.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
> Implement matched event

- rmw_cyclonedds_cpp/src/rmw_node.cpp
This PR is part of the runtime interface reflection subscription feature of REP-2011: https://github.com/ros2/ros2/issues/1374
The PRs for REP-2011 introduced new rmw interfaces. rmw_cyclonedds will not support dynamic subscription yet, but must have the rmw interfaces implemented, so this PR adds stub implementations.
> Runtime Interface Reflection: rmw_cyclonedds stubs for new RMW interfaces

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Part of https://github.com/ros2/ros2_tracing/issues/18
Requires https://github.com/ros2/ros2_tracing/pull/56
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
> Use TRACETOOLS_ prefix for tracepoint-related macros

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Just trigger the `rmw_publish` tracepoint for loaned message publications too.
> Instrument loaned message publication code path

- rmw_cyclonedds_cpp/src/rmw_node.cpp
In particular, in the type-hash code we can handle a failure to encode or parse the type hash from the user data.  Once we've handled it, and printed out an error about it, we should clear it because we are going to continue on and something else down the line might have an error.
This will avoid errors like:
This error state is being overwritten:
<old message>
with this new error message:
<new message>
> Clear out errors once we have handled them.

- rmw_cyclonedds_cpp/CMakeLists.txt
The most important bit in here is to set
CMAKE_CXX_STANDARD_REQUIRED to ON, so it builds in C++17 mode with clang.  Besides that, cleanup a comment, and get rid of extra calls to target_link_libraries that aren't required (we can just combine that all into one call).
> Minor revamp of the CMakeLists.txt.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
this PR is for service counts using it's name like topic.
Related to https://github.com/ros2/ros2cli/pull/771
Signed-off-by: leeminju531 <dlalswn531@naver.com>
> Add rmw count clients,services impl

- rmw_cyclonedds_cpp/src/rmw_node.cpp
It depends on https://github.com/ros2/rmw_dds_common/pull/73
> avoid using dds common public mutex directly

- rmw_cyclonedds_cpp/src/rmw_node.cpp
- rmw_cyclonedds_cpp/src/serdes.hpp
The main goal here is to sidestep differences between uncrustify 0.72 and 0.78.  However, I realized that a lot of these macros were either duplicating functionality we already had, or were just as long as "inlining" the code would be.  Just get rid of these macros.
In the one place that we can't do this, just mark the macro as not to be indented by uncrustify.
> Remove a bunch of unnecessary macros.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
Please, refer to https://github.com/ros2/rclcpp/pull/2448 .
I have added the following trace points.
- `__rmw_publish_serialized_message()`
- tracepoint : rmw_publish
- `_take_serialized_message()`
- tracepoint : rmw_take
> Add tracepoint for publish/subscribe serialized message

- rmw_cyclonedds_cpp/src/rmw_node.cpp
- Relates https://github.com/ros2/rosbag2/pull/1641
- Fixes https://github.com/ros2/rosbag2/issues/1638
> Set received_timestamp to system_clock::now() in message_info

- rmw_cyclonedds_cpp/src/rmw_node.cpp
https://github.com/ros2/rmw/pull/275 changed the `rmw_destroy_wait_set()` API documentation to indicate that it returns `RMW_RET_INVALID_ARGUMENT` if `wait_set` is `NULL`. However, this wasn't the case in practice in the implementations of `rmw_destroy_wait_set()` or in the relevant test.
Change the implementation here to return `RMW_RET_INVALID_ARGUMENT`.
Requires https://github.com/ros2/rmw_implementation/pull/234
> Make rmw_destroy_wait_set return RMW_RET_INVALID_ARGUMENT

- rmw_cyclonedds_cpp/src/rmw_node.cpp
`rmw_namespace_validation_result_string()` -- not `rmw_node_name_validation_result_string()` -- should be called with the validation result from `rmw_validate_namespace()`.
In practice, this meant that the reason given might have been `"unknown result code for rmw node name validation"` given that `rmw_node_name_validation_result_string()` doesn't know about all validation results from `rmw_validate_namespace()`. However, I believe that we don't test these error messages anywhere and rarely rely on them, so it doesn't/shouldn't affect any tests or functionality.
Related PRs:
* https://github.com/ros2/rmw_fastrtps/pull/765
* https://github.com/ros2/rmw_connextdds/pull/151
* https://github.com/ros2/rmw_zenoh/pull/196
> Use rmw_namespace_validation_result_string() in rmw_create_node

- rmw_cyclonedds_cpp/src/rmw_node.cpp
https://github.com/ros2/rmw/pull/277 changed the `rmw_service_server_is_available()` API documentation to indicate that it returns `RMW_RET_INVALID_ARGUMENT` if `node`, `client`, or `is_available` are `NULL`. However, this wasn't the case in practice in the implementations of `rmw_service_server_is_available()` or in the relevant test.
Change the implementation here to return `RMW_RET_INVALID_ARGUMENT`.
Requires https://github.com/ros2/rmw_implementation/pull/231
> Make rmw_service_server_is_available return RMW_RET_INVALID_ARGUMENT

- rmw_cyclonedds_cpp/src/rmw_node.cpp
When a guard condition goes active, we have to remember to increase the trig_idx so we look at the next trigger. Otherwise, we can get into situations where we skip a triggered member.
This is a regression from #482 .  This fixes #494 and should also fix https://github.com/ros2/rclcpp/issues/2502 .  @Crola1702 FYI.
This should also be backported to Jazzy.
> Fix the triggering of guard conditions.

- rmw_cyclonedds_cpp/src/rmw_node.cpp
minor fix to remove redundant check and lint, aligns with https://github.com/ros2/rmw/pull/345
> use RMW_GID_STORAGE_SIZE to client_service_id_t.

- rmw_cyclonedds_cpp/src/Serialization.cpp
- rmw_cyclonedds_cpp/src/TypeSupport2.hpp
See https://github.com/ros2/rosidl_dynamic_typesupport/issues/11 for the motivation on doing this.
> Drop support for float128.
